/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/emitter.c"

int bridge_yaml_emitter_set_emitter_error(yaml_emitter_t *emitter, const char *problem) {
    return yaml_emitter_set_emitter_error(emitter, problem);
}

int bridge_yaml_emitter_need_more_events(yaml_emitter_t *emitter) {
    return yaml_emitter_need_more_events(emitter);
}

int bridge_yaml_emitter_append_tag_directive(yaml_emitter_t *emitter, yaml_tag_directive_t value, int allow_duplicates) {
    return yaml_emitter_append_tag_directive(emitter, value, allow_duplicates);
}

int bridge_yaml_emitter_increase_indent(yaml_emitter_t *emitter, int flow, int indentless) {
    return yaml_emitter_increase_indent(emitter, flow, indentless);
}

int bridge_yaml_emitter_state_machine(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_state_machine(emitter, event);
}

int bridge_yaml_emitter_emit_stream_start(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_emit_stream_start(emitter, event);
}

int bridge_yaml_emitter_emit_document_start(yaml_emitter_t *emitter, yaml_event_t *event, int first) {
    return yaml_emitter_emit_document_start(emitter, event, first);
}

int bridge_yaml_emitter_emit_document_content(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_emit_document_content(emitter, event);
}

int bridge_yaml_emitter_emit_document_end(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_emit_document_end(emitter, event);
}

int bridge_yaml_emitter_emit_flow_sequence_item(yaml_emitter_t *emitter, yaml_event_t *event, int first) {
    return yaml_emitter_emit_flow_sequence_item(emitter, event, first);
}

int bridge_yaml_emitter_emit_flow_mapping_key(yaml_emitter_t *emitter, yaml_event_t *event, int first) {
    return yaml_emitter_emit_flow_mapping_key(emitter, event, first);
}

int bridge_yaml_emitter_emit_flow_mapping_value(yaml_emitter_t *emitter, yaml_event_t *event, int simple) {
    return yaml_emitter_emit_flow_mapping_value(emitter, event, simple);
}

int bridge_yaml_emitter_emit_block_sequence_item(yaml_emitter_t *emitter, yaml_event_t *event, int first) {
    return yaml_emitter_emit_block_sequence_item(emitter, event, first);
}

int bridge_yaml_emitter_emit_block_mapping_key(yaml_emitter_t *emitter, yaml_event_t *event, int first) {
    return yaml_emitter_emit_block_mapping_key(emitter, event, first);
}

int bridge_yaml_emitter_emit_block_mapping_value(yaml_emitter_t *emitter, yaml_event_t *event, int simple) {
    return yaml_emitter_emit_block_mapping_value(emitter, event, simple);
}

int bridge_yaml_emitter_emit_node(yaml_emitter_t *emitter, yaml_event_t *event, int root, int sequence, int mapping, int simple_key) {
    return yaml_emitter_emit_node(emitter, event, root, sequence, mapping, simple_key);
}

int bridge_yaml_emitter_emit_alias(yaml_emitter_t *emitter, yaml_event_t *event __attribute__((unused))) {
    return yaml_emitter_emit_alias(emitter, event);
}

int bridge_yaml_emitter_emit_scalar(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_emit_scalar(emitter, event);
}

int bridge_yaml_emitter_emit_sequence_start(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_emit_sequence_start(emitter, event);
}

int bridge_yaml_emitter_emit_mapping_start(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_emit_mapping_start(emitter, event);
}

int bridge_yaml_emitter_check_empty_document(yaml_emitter_t *emitter __attribute__((unused))) {
    return yaml_emitter_check_empty_document(emitter);
}

int bridge_yaml_emitter_check_empty_sequence(yaml_emitter_t *emitter) {
    return yaml_emitter_check_empty_sequence(emitter);
}

int bridge_yaml_emitter_check_empty_mapping(yaml_emitter_t *emitter) {
    return yaml_emitter_check_empty_mapping(emitter);
}

int bridge_yaml_emitter_check_simple_key(yaml_emitter_t *emitter) {
    return yaml_emitter_check_simple_key(emitter);
}

int bridge_yaml_emitter_select_scalar_style(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_select_scalar_style(emitter, event);
}

int bridge_yaml_emitter_process_anchor(yaml_emitter_t *emitter) {
    return yaml_emitter_process_anchor(emitter);
}

int bridge_yaml_emitter_process_tag(yaml_emitter_t *emitter) {
    return yaml_emitter_process_tag(emitter);
}

int bridge_yaml_emitter_process_scalar(yaml_emitter_t *emitter) {
    return yaml_emitter_process_scalar(emitter);
}

int bridge_yaml_emitter_analyze_version_directive(yaml_emitter_t *emitter, yaml_version_directive_t version_directive) {
    return yaml_emitter_analyze_version_directive(emitter, version_directive);
}

int bridge_yaml_emitter_analyze_tag_directive(yaml_emitter_t *emitter, yaml_tag_directive_t tag_directive) {
    return yaml_emitter_analyze_tag_directive(emitter, tag_directive);
}

int bridge_yaml_emitter_analyze_anchor(yaml_emitter_t *emitter, yaml_char_t *anchor, int alias) {
    return yaml_emitter_analyze_anchor(emitter, anchor, alias);
}

int bridge_yaml_emitter_analyze_tag(yaml_emitter_t *emitter, yaml_char_t *tag) {
    return yaml_emitter_analyze_tag(emitter, tag);
}

int bridge_yaml_emitter_analyze_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length) {
    return yaml_emitter_analyze_scalar(emitter, value, length);
}

int bridge_yaml_emitter_analyze_event(yaml_emitter_t *emitter, yaml_event_t *event) {
    return yaml_emitter_analyze_event(emitter, event);
}

int bridge_yaml_emitter_write_bom(yaml_emitter_t *emitter) {
    return yaml_emitter_write_bom(emitter);
}

int bridge_yaml_emitter_write_indent(yaml_emitter_t *emitter) {
    return yaml_emitter_write_indent(emitter);
}

int bridge_yaml_emitter_write_indicator(yaml_emitter_t *emitter, const char *indicator, int need_whitespace, int is_whitespace, int is_indention) {
    return yaml_emitter_write_indicator(emitter, indicator, need_whitespace, is_whitespace, is_indention);
}

int bridge_yaml_emitter_write_anchor(yaml_emitter_t *emitter, yaml_char_t *value, size_t length) {
    return yaml_emitter_write_anchor(emitter, value, length);
}

int bridge_yaml_emitter_write_tag_handle(yaml_emitter_t *emitter, yaml_char_t *value, size_t length) {
    return yaml_emitter_write_tag_handle(emitter, value, length);
}

int bridge_yaml_emitter_write_tag_content(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int need_whitespace) {
    return yaml_emitter_write_tag_content(emitter, value, length, need_whitespace);
}

int bridge_yaml_emitter_write_plain_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int allow_breaks) {
    return yaml_emitter_write_plain_scalar(emitter, value, length, allow_breaks);
}

int bridge_yaml_emitter_write_single_quoted_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int allow_breaks) {
    return yaml_emitter_write_single_quoted_scalar(emitter, value, length, allow_breaks);
}

int bridge_yaml_emitter_write_double_quoted_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int allow_breaks) {
    return yaml_emitter_write_double_quoted_scalar(emitter, value, length, allow_breaks);
}

int bridge_yaml_emitter_write_block_scalar_hints(yaml_emitter_t *emitter, yaml_string_t string) {
    return yaml_emitter_write_block_scalar_hints(emitter, string);
}

int bridge_yaml_emitter_write_literal_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length) {
    return yaml_emitter_write_literal_scalar(emitter, value, length);
}

int bridge_yaml_emitter_write_folded_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length) {
    return yaml_emitter_write_folded_scalar(emitter, value, length);
}
