/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/loader.c"

int bridge_yaml_parser_set_composer_error(yaml_parser_t *parser, const char *problem, yaml_mark_t problem_mark) {
    return yaml_parser_set_composer_error(parser, problem, problem_mark);
}

int bridge_yaml_parser_set_composer_error_context(yaml_parser_t *parser, const char *context, yaml_mark_t context_mark, const char *problem, yaml_mark_t problem_mark) {
    return yaml_parser_set_composer_error_context(parser, context, context_mark, problem, problem_mark);
}

void bridge_yaml_parser_delete_aliases(yaml_parser_t *parser) {
    yaml_parser_delete_aliases(parser);
}

int bridge_yaml_parser_load_document(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_load_document(parser, event);
}

int bridge_yaml_parser_load_nodes(yaml_parser_t *parser, struct loader_ctx *ctx) {
    return yaml_parser_load_nodes(parser, ctx);
}

int bridge_yaml_parser_register_anchor(yaml_parser_t *parser, int index, yaml_char_t *anchor) {
    return yaml_parser_register_anchor(parser, index, anchor);
}

int bridge_yaml_parser_load_node_add(yaml_parser_t *parser, struct loader_ctx *ctx, int index) {
    return yaml_parser_load_node_add(parser, ctx, index);
}

int bridge_yaml_parser_load_alias(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx) {
    return yaml_parser_load_alias(parser, event, ctx);
}

int bridge_yaml_parser_load_scalar(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx) {
    return yaml_parser_load_scalar(parser, event, ctx);
}

int bridge_yaml_parser_load_sequence(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx) {
    return yaml_parser_load_sequence(parser, event, ctx);
}

int bridge_yaml_parser_load_sequence_end(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx) {
    return yaml_parser_load_sequence_end(parser, event, ctx);
}

int bridge_yaml_parser_load_mapping(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx) {
    return yaml_parser_load_mapping(parser, event, ctx);
}

int bridge_yaml_parser_load_mapping_end(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx) {
    return yaml_parser_load_mapping_end(parser, event, ctx);
}
