/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/dumper.c"

void bridge_yaml_emitter_delete_document_and_anchors(yaml_emitter_t *emitter) {
    yaml_emitter_delete_document_and_anchors(emitter);
}

void bridge_yaml_emitter_anchor_node(yaml_emitter_t *emitter, int index) {
    yaml_emitter_anchor_node(emitter, index);
}

yaml_char_t * bridge_yaml_emitter_generate_anchor(yaml_emitter_t *emitter __attribute__((unused)), int anchor_id) {
    return yaml_emitter_generate_anchor(emitter, anchor_id);
}

int bridge_yaml_emitter_dump_node(yaml_emitter_t *emitter, int index) {
    return yaml_emitter_dump_node(emitter, index);
}

int bridge_yaml_emitter_dump_alias(yaml_emitter_t *emitter, yaml_char_t *anchor) {
    return yaml_emitter_dump_alias(emitter, anchor);
}

int bridge_yaml_emitter_dump_scalar(yaml_emitter_t *emitter, yaml_node_t *node, yaml_char_t *anchor) {
    return yaml_emitter_dump_scalar(emitter, node, anchor);
}

int bridge_yaml_emitter_dump_sequence(yaml_emitter_t *emitter, yaml_node_t *node, yaml_char_t *anchor) {
    return yaml_emitter_dump_sequence(emitter, node, anchor);
}

int bridge_yaml_emitter_dump_mapping(yaml_emitter_t *emitter, yaml_node_t *node, yaml_char_t *anchor) {
    return yaml_emitter_dump_mapping(emitter, node, anchor);
}
