/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/scanner.c"

int bridge_yaml_parser_set_scanner_error(yaml_parser_t *parser, const char *context, yaml_mark_t context_mark, const char *problem) {
    return yaml_parser_set_scanner_error(parser, context, context_mark, problem);
}

int bridge_yaml_parser_fetch_next_token(yaml_parser_t *parser) {
    return yaml_parser_fetch_next_token(parser);
}

int bridge_yaml_parser_stale_simple_keys(yaml_parser_t *parser) {
    return yaml_parser_stale_simple_keys(parser);
}

int bridge_yaml_parser_save_simple_key(yaml_parser_t *parser) {
    return yaml_parser_save_simple_key(parser);
}

int bridge_yaml_parser_remove_simple_key(yaml_parser_t *parser) {
    return yaml_parser_remove_simple_key(parser);
}

int bridge_yaml_parser_increase_flow_level(yaml_parser_t *parser) {
    return yaml_parser_increase_flow_level(parser);
}

int bridge_yaml_parser_decrease_flow_level(yaml_parser_t *parser) {
    return yaml_parser_decrease_flow_level(parser);
}

int bridge_yaml_parser_roll_indent(yaml_parser_t *parser, ptrdiff_t column, ptrdiff_t number, yaml_token_type_t type, yaml_mark_t mark) {
    return yaml_parser_roll_indent(parser, column, number, type, mark);
}

int bridge_yaml_parser_unroll_indent(yaml_parser_t *parser, ptrdiff_t column) {
    return yaml_parser_unroll_indent(parser, column);
}

int bridge_yaml_parser_fetch_stream_start(yaml_parser_t *parser) {
    return yaml_parser_fetch_stream_start(parser);
}

int bridge_yaml_parser_fetch_stream_end(yaml_parser_t *parser) {
    return yaml_parser_fetch_stream_end(parser);
}

int bridge_yaml_parser_fetch_directive(yaml_parser_t *parser) {
    return yaml_parser_fetch_directive(parser);
}

int bridge_yaml_parser_fetch_document_indicator(yaml_parser_t *parser, yaml_token_type_t type) {
    return yaml_parser_fetch_document_indicator(parser, type);
}

int bridge_yaml_parser_fetch_flow_collection_start(yaml_parser_t *parser, yaml_token_type_t type) {
    return yaml_parser_fetch_flow_collection_start(parser, type);
}

int bridge_yaml_parser_fetch_flow_collection_end(yaml_parser_t *parser, yaml_token_type_t type) {
    return yaml_parser_fetch_flow_collection_end(parser, type);
}

int bridge_yaml_parser_fetch_flow_entry(yaml_parser_t *parser) {
    return yaml_parser_fetch_flow_entry(parser);
}

int bridge_yaml_parser_fetch_block_entry(yaml_parser_t *parser) {
    return yaml_parser_fetch_block_entry(parser);
}

int bridge_yaml_parser_fetch_key(yaml_parser_t *parser) {
    return yaml_parser_fetch_key(parser);
}

int bridge_yaml_parser_fetch_value(yaml_parser_t *parser) {
    return yaml_parser_fetch_value(parser);
}

int bridge_yaml_parser_fetch_anchor(yaml_parser_t *parser, yaml_token_type_t type) {
    return yaml_parser_fetch_anchor(parser, type);
}

int bridge_yaml_parser_fetch_tag(yaml_parser_t *parser) {
    return yaml_parser_fetch_tag(parser);
}

int bridge_yaml_parser_fetch_block_scalar(yaml_parser_t *parser, int literal) {
    return yaml_parser_fetch_block_scalar(parser, literal);
}

int bridge_yaml_parser_fetch_flow_scalar(yaml_parser_t *parser, int single) {
    return yaml_parser_fetch_flow_scalar(parser, single);
}

int bridge_yaml_parser_fetch_plain_scalar(yaml_parser_t *parser) {
    return yaml_parser_fetch_plain_scalar(parser);
}

int bridge_yaml_parser_scan_to_next_token(yaml_parser_t *parser) {
    return yaml_parser_scan_to_next_token(parser);
}

int bridge_yaml_parser_scan_directive(yaml_parser_t *parser, yaml_token_t *token) {
    return yaml_parser_scan_directive(parser, token);
}

int bridge_yaml_parser_scan_directive_name(yaml_parser_t *parser, yaml_mark_t start_mark, yaml_char_t **name) {
    return yaml_parser_scan_directive_name(parser, start_mark, name);
}

int bridge_yaml_parser_scan_version_directive_value(yaml_parser_t *parser, yaml_mark_t start_mark, int *major, int *minor) {
    return yaml_parser_scan_version_directive_value(parser, start_mark, major, minor);
}

int bridge_yaml_parser_scan_version_directive_number(yaml_parser_t *parser, yaml_mark_t start_mark, int *number) {
    return yaml_parser_scan_version_directive_number(parser, start_mark, number);
}

int bridge_yaml_parser_scan_tag_directive_value(yaml_parser_t *parser, yaml_mark_t start_mark, yaml_char_t **handle, yaml_char_t **prefix) {
    return yaml_parser_scan_tag_directive_value(parser, start_mark, handle, prefix);
}

int bridge_yaml_parser_scan_anchor(yaml_parser_t *parser, yaml_token_t *token, yaml_token_type_t type) {
    return yaml_parser_scan_anchor(parser, token, type);
}

int bridge_yaml_parser_scan_tag(yaml_parser_t *parser, yaml_token_t *token) {
    return yaml_parser_scan_tag(parser, token);
}

int bridge_yaml_parser_scan_tag_handle(yaml_parser_t *parser, int directive, yaml_mark_t start_mark, yaml_char_t **handle) {
    return yaml_parser_scan_tag_handle(parser, directive, start_mark, handle);
}

int bridge_yaml_parser_scan_tag_uri(yaml_parser_t *parser, int uri_char, int directive, yaml_char_t *head, yaml_mark_t start_mark, yaml_char_t **uri) {
    return yaml_parser_scan_tag_uri(parser, uri_char, directive, head, start_mark, uri);
}

int bridge_yaml_parser_scan_uri_escapes(yaml_parser_t *parser, int directive, yaml_mark_t start_mark, yaml_string_t *string) {
    return yaml_parser_scan_uri_escapes(parser, directive, start_mark, string);
}

int bridge_yaml_parser_scan_block_scalar(yaml_parser_t *parser, yaml_token_t *token, int literal) {
    return yaml_parser_scan_block_scalar(parser, token, literal);
}

int bridge_yaml_parser_scan_block_scalar_breaks(yaml_parser_t *parser, int *indent, yaml_string_t *breaks, yaml_mark_t start_mark, yaml_mark_t *end_mark) {
    return yaml_parser_scan_block_scalar_breaks(parser, indent, breaks, start_mark, end_mark);
}

int bridge_yaml_parser_scan_flow_scalar(yaml_parser_t *parser, yaml_token_t *token, int single) {
    return yaml_parser_scan_flow_scalar(parser, token, single);
}

int bridge_yaml_parser_scan_plain_scalar(yaml_parser_t *parser, yaml_token_t *token) {
    return yaml_parser_scan_plain_scalar(parser, token);
}
