/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/writer.c"

int bridge_yaml_emitter_set_writer_error(yaml_emitter_t *emitter, const char *problem) {
    return yaml_emitter_set_writer_error(emitter, problem);
}
