/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/reader.c"

int bridge_yaml_parser_set_reader_error(yaml_parser_t *parser, const char *problem, size_t offset, int value) {
    return yaml_parser_set_reader_error(parser, problem, offset, value);
}

int bridge_yaml_parser_determine_encoding(yaml_parser_t *parser) {
    return yaml_parser_determine_encoding(parser);
}

int bridge_yaml_parser_update_raw_buffer(yaml_parser_t *parser) {
    return yaml_parser_update_raw_buffer(parser);
}
