/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
/* Bridge wrappers exposing libyaml static functions for tests. */
#ifndef TEST_BRIDGE_H
#define TEST_BRIDGE_H

#include <stddef.h>       /* ptrdiff_t */
#include "yaml.h"
/* yaml_string_t is an internal type defined in yaml_private.h. Compiling code
 * that uses these bridges requires: -DHAVE_CONFIG_H=1 -I<libyaml>/src -I<libyaml>/build/include */
#include "yaml_private.h"

#ifdef __cplusplus
extern "C" {
#endif

/* === api.c === */
int bridge_yaml_string_read_handler(void *data, unsigned char *buffer, size_t size, size_t *size_read);
int bridge_yaml_file_read_handler(void *data, unsigned char *buffer, size_t size, size_t *size_read);
int bridge_yaml_string_write_handler(void *data, unsigned char *buffer, size_t size);
int bridge_yaml_file_write_handler(void *data, unsigned char *buffer, size_t size);
int bridge_yaml_check_utf8(const yaml_char_t *start, size_t length);

/* === dumper.c === */
void bridge_yaml_emitter_delete_document_and_anchors(yaml_emitter_t *emitter);
void bridge_yaml_emitter_anchor_node(yaml_emitter_t *emitter, int index);
yaml_char_t *bridge_yaml_emitter_generate_anchor(yaml_emitter_t *emitter, int anchor_id);
int bridge_yaml_emitter_dump_node(yaml_emitter_t *emitter, int index);
int bridge_yaml_emitter_dump_alias(yaml_emitter_t *emitter, yaml_char_t *anchor);
int bridge_yaml_emitter_dump_scalar(yaml_emitter_t *emitter, yaml_node_t *node, yaml_char_t *anchor);
int bridge_yaml_emitter_dump_sequence(yaml_emitter_t *emitter, yaml_node_t *node, yaml_char_t *anchor);
int bridge_yaml_emitter_dump_mapping(yaml_emitter_t *emitter, yaml_node_t *node, yaml_char_t *anchor);

/* === emitter.c === */
int bridge_yaml_emitter_set_emitter_error(yaml_emitter_t *emitter, const char *problem);
int bridge_yaml_emitter_need_more_events(yaml_emitter_t *emitter);
int bridge_yaml_emitter_append_tag_directive(yaml_emitter_t *emitter, yaml_tag_directive_t value, int allow_duplicates);
int bridge_yaml_emitter_increase_indent(yaml_emitter_t *emitter, int flow, int indentless);
int bridge_yaml_emitter_state_machine(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_stream_start(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_document_start(yaml_emitter_t *emitter, yaml_event_t *event, int first);
int bridge_yaml_emitter_emit_document_content(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_document_end(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_flow_sequence_item(yaml_emitter_t *emitter, yaml_event_t *event, int first);
int bridge_yaml_emitter_emit_flow_mapping_key(yaml_emitter_t *emitter, yaml_event_t *event, int first);
int bridge_yaml_emitter_emit_flow_mapping_value(yaml_emitter_t *emitter, yaml_event_t *event, int simple);
int bridge_yaml_emitter_emit_block_sequence_item(yaml_emitter_t *emitter, yaml_event_t *event, int first);
int bridge_yaml_emitter_emit_block_mapping_key(yaml_emitter_t *emitter, yaml_event_t *event, int first);
int bridge_yaml_emitter_emit_block_mapping_value(yaml_emitter_t *emitter, yaml_event_t *event, int simple);
int bridge_yaml_emitter_emit_node(yaml_emitter_t *emitter, yaml_event_t *event, int root, int sequence, int mapping, int simple_key);
int bridge_yaml_emitter_emit_alias(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_scalar(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_sequence_start(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_emit_mapping_start(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_check_empty_document(yaml_emitter_t *emitter);
int bridge_yaml_emitter_check_empty_sequence(yaml_emitter_t *emitter);
int bridge_yaml_emitter_check_empty_mapping(yaml_emitter_t *emitter);
int bridge_yaml_emitter_check_simple_key(yaml_emitter_t *emitter);
int bridge_yaml_emitter_select_scalar_style(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_process_anchor(yaml_emitter_t *emitter);
int bridge_yaml_emitter_process_tag(yaml_emitter_t *emitter);
int bridge_yaml_emitter_process_scalar(yaml_emitter_t *emitter);
int bridge_yaml_emitter_analyze_version_directive(yaml_emitter_t *emitter, yaml_version_directive_t version_directive);
int bridge_yaml_emitter_analyze_tag_directive(yaml_emitter_t *emitter, yaml_tag_directive_t tag_directive);
int bridge_yaml_emitter_analyze_anchor(yaml_emitter_t *emitter, yaml_char_t *anchor, int alias);
int bridge_yaml_emitter_analyze_tag(yaml_emitter_t *emitter, yaml_char_t *tag);
int bridge_yaml_emitter_analyze_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length);
int bridge_yaml_emitter_analyze_event(yaml_emitter_t *emitter, yaml_event_t *event);
int bridge_yaml_emitter_write_bom(yaml_emitter_t *emitter);
int bridge_yaml_emitter_write_indent(yaml_emitter_t *emitter);
int bridge_yaml_emitter_write_indicator(yaml_emitter_t *emitter, const char *indicator, int need_whitespace, int is_whitespace, int is_indention);
int bridge_yaml_emitter_write_anchor(yaml_emitter_t *emitter, yaml_char_t *value, size_t length);
int bridge_yaml_emitter_write_tag_handle(yaml_emitter_t *emitter, yaml_char_t *value, size_t length);
int bridge_yaml_emitter_write_tag_content(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int need_whitespace);
int bridge_yaml_emitter_write_plain_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int allow_breaks);
int bridge_yaml_emitter_write_single_quoted_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int allow_breaks);
int bridge_yaml_emitter_write_double_quoted_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length, int allow_breaks);
int bridge_yaml_emitter_write_block_scalar_hints(yaml_emitter_t *emitter, yaml_string_t string);
int bridge_yaml_emitter_write_literal_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length);
int bridge_yaml_emitter_write_folded_scalar(yaml_emitter_t *emitter, yaml_char_t *value, size_t length);

/* === loader.c === */
int bridge_yaml_parser_set_composer_error(yaml_parser_t *parser, const char *problem, yaml_mark_t problem_mark);
int bridge_yaml_parser_set_composer_error_context(yaml_parser_t *parser, const char *context, yaml_mark_t context_mark, const char *problem, yaml_mark_t problem_mark);
void bridge_yaml_parser_delete_aliases(yaml_parser_t *parser);
int bridge_yaml_parser_load_document(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_load_nodes(yaml_parser_t *parser, struct loader_ctx *ctx);
int bridge_yaml_parser_register_anchor(yaml_parser_t *parser, int index, yaml_char_t *anchor);
int bridge_yaml_parser_load_node_add(yaml_parser_t *parser, struct loader_ctx *ctx, int index);
int bridge_yaml_parser_load_alias(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx);
int bridge_yaml_parser_load_scalar(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx);
int bridge_yaml_parser_load_sequence(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx);
int bridge_yaml_parser_load_sequence_end(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx);
int bridge_yaml_parser_load_mapping(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx);
int bridge_yaml_parser_load_mapping_end(yaml_parser_t *parser, yaml_event_t *event, struct loader_ctx *ctx);

/* === parser.c === */
int bridge_yaml_parser_set_parser_error(yaml_parser_t *parser, const char *problem, yaml_mark_t problem_mark);
int bridge_yaml_parser_set_parser_error_context(yaml_parser_t *parser, const char *context, yaml_mark_t context_mark, const char *problem, yaml_mark_t problem_mark);
int bridge_yaml_maximum_level_reached(yaml_parser_t *parser, yaml_mark_t context_mark, yaml_mark_t problem_mark);
int bridge_yaml_parser_state_machine(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_stream_start(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_document_start(yaml_parser_t *parser, yaml_event_t *event, int implicit);
int bridge_yaml_parser_parse_document_content(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_document_end(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_node(yaml_parser_t *parser, yaml_event_t *event, int block, int indentless_sequence);
int bridge_yaml_parser_parse_block_sequence_entry(yaml_parser_t *parser, yaml_event_t *event, int first);
int bridge_yaml_parser_parse_indentless_sequence_entry(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_block_mapping_key(yaml_parser_t *parser, yaml_event_t *event, int first);
int bridge_yaml_parser_parse_block_mapping_value(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_flow_sequence_entry(yaml_parser_t *parser, yaml_event_t *event, int first);
int bridge_yaml_parser_parse_flow_sequence_entry_mapping_key(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_flow_sequence_entry_mapping_value(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_flow_sequence_entry_mapping_end(yaml_parser_t *parser, yaml_event_t *event);
int bridge_yaml_parser_parse_flow_mapping_key(yaml_parser_t *parser, yaml_event_t *event, int first);
int bridge_yaml_parser_parse_flow_mapping_value(yaml_parser_t *parser, yaml_event_t *event, int empty);
int bridge_yaml_parser_process_empty_scalar(yaml_parser_t *parser, yaml_event_t *event, yaml_mark_t mark);
int bridge_yaml_parser_process_directives(yaml_parser_t *parser, yaml_version_directive_t **version_directive_ref, yaml_tag_directive_t **tag_directives_start_ref, yaml_tag_directive_t **tag_directives_end_ref);
int bridge_yaml_parser_append_tag_directive(yaml_parser_t *parser, yaml_tag_directive_t value, int allow_duplicates, yaml_mark_t mark);

/* === reader.c === */
int bridge_yaml_parser_set_reader_error(yaml_parser_t *parser, const char *problem, size_t offset, int value);
int bridge_yaml_parser_determine_encoding(yaml_parser_t *parser);
int bridge_yaml_parser_update_raw_buffer(yaml_parser_t *parser);

/* === scanner.c === */
int bridge_yaml_parser_set_scanner_error(yaml_parser_t *parser, const char *context, yaml_mark_t context_mark, const char *problem);
int bridge_yaml_parser_fetch_next_token(yaml_parser_t *parser);
int bridge_yaml_parser_stale_simple_keys(yaml_parser_t *parser);
int bridge_yaml_parser_save_simple_key(yaml_parser_t *parser);
int bridge_yaml_parser_remove_simple_key(yaml_parser_t *parser);
int bridge_yaml_parser_increase_flow_level(yaml_parser_t *parser);
int bridge_yaml_parser_decrease_flow_level(yaml_parser_t *parser);
int bridge_yaml_parser_roll_indent(yaml_parser_t *parser, ptrdiff_t column, ptrdiff_t number, yaml_token_type_t type, yaml_mark_t mark);
int bridge_yaml_parser_unroll_indent(yaml_parser_t *parser, ptrdiff_t column);
int bridge_yaml_parser_fetch_stream_start(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_stream_end(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_directive(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_document_indicator(yaml_parser_t *parser, yaml_token_type_t type);
int bridge_yaml_parser_fetch_flow_collection_start(yaml_parser_t *parser, yaml_token_type_t type);
int bridge_yaml_parser_fetch_flow_collection_end(yaml_parser_t *parser, yaml_token_type_t type);
int bridge_yaml_parser_fetch_flow_entry(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_block_entry(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_key(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_value(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_anchor(yaml_parser_t *parser, yaml_token_type_t type);
int bridge_yaml_parser_fetch_tag(yaml_parser_t *parser);
int bridge_yaml_parser_fetch_block_scalar(yaml_parser_t *parser, int literal);
int bridge_yaml_parser_fetch_flow_scalar(yaml_parser_t *parser, int single);
int bridge_yaml_parser_fetch_plain_scalar(yaml_parser_t *parser);
int bridge_yaml_parser_scan_to_next_token(yaml_parser_t *parser);
int bridge_yaml_parser_scan_directive(yaml_parser_t *parser, yaml_token_t *token);
int bridge_yaml_parser_scan_directive_name(yaml_parser_t *parser, yaml_mark_t start_mark, yaml_char_t **name);
int bridge_yaml_parser_scan_version_directive_value(yaml_parser_t *parser, yaml_mark_t start_mark, int *major, int *minor);
int bridge_yaml_parser_scan_version_directive_number(yaml_parser_t *parser, yaml_mark_t start_mark, int *number);
int bridge_yaml_parser_scan_tag_directive_value(yaml_parser_t *parser, yaml_mark_t start_mark, yaml_char_t **handle, yaml_char_t **prefix);
int bridge_yaml_parser_scan_anchor(yaml_parser_t *parser, yaml_token_t *token, yaml_token_type_t type);
int bridge_yaml_parser_scan_tag(yaml_parser_t *parser, yaml_token_t *token);
int bridge_yaml_parser_scan_tag_handle(yaml_parser_t *parser, int directive, yaml_mark_t start_mark, yaml_char_t **handle);
int bridge_yaml_parser_scan_tag_uri(yaml_parser_t *parser, int uri_char, int directive, yaml_char_t *head, yaml_mark_t start_mark, yaml_char_t **uri);
int bridge_yaml_parser_scan_uri_escapes(yaml_parser_t *parser, int directive, yaml_mark_t start_mark, yaml_string_t *string);
int bridge_yaml_parser_scan_block_scalar(yaml_parser_t *parser, yaml_token_t *token, int literal);
int bridge_yaml_parser_scan_block_scalar_breaks(yaml_parser_t *parser, int *indent, yaml_string_t *breaks, yaml_mark_t start_mark, yaml_mark_t *end_mark);
int bridge_yaml_parser_scan_flow_scalar(yaml_parser_t *parser, yaml_token_t *token, int single);
int bridge_yaml_parser_scan_plain_scalar(yaml_parser_t *parser, yaml_token_t *token);

/* === writer.c === */
int bridge_yaml_emitter_set_writer_error(yaml_emitter_t *emitter, const char *problem);

#ifdef __cplusplus
}
#endif

#endif /* TEST_BRIDGE_H */