/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/parser.c"

int bridge_yaml_parser_set_parser_error(yaml_parser_t *parser, const char *problem, yaml_mark_t problem_mark) {
    return yaml_parser_set_parser_error(parser, problem, problem_mark);
}

int bridge_yaml_parser_set_parser_error_context(yaml_parser_t *parser, const char *context, yaml_mark_t context_mark, const char *problem, yaml_mark_t problem_mark) {
    return yaml_parser_set_parser_error_context(parser, context, context_mark, problem, problem_mark);
}

int bridge_yaml_maximum_level_reached(yaml_parser_t *parser, yaml_mark_t context_mark, yaml_mark_t problem_mark) {
    return yaml_maximum_level_reached(parser, context_mark, problem_mark);
}

int bridge_yaml_parser_state_machine(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_state_machine(parser, event);
}

int bridge_yaml_parser_parse_stream_start(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_stream_start(parser, event);
}

int bridge_yaml_parser_parse_document_start(yaml_parser_t *parser, yaml_event_t *event, int implicit) {
    return yaml_parser_parse_document_start(parser, event, implicit);
}

int bridge_yaml_parser_parse_document_content(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_document_content(parser, event);
}

int bridge_yaml_parser_parse_document_end(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_document_end(parser, event);
}

int bridge_yaml_parser_parse_node(yaml_parser_t *parser, yaml_event_t *event, int block, int indentless_sequence) {
    return yaml_parser_parse_node(parser, event, block, indentless_sequence);
}

int bridge_yaml_parser_parse_block_sequence_entry(yaml_parser_t *parser, yaml_event_t *event, int first) {
    return yaml_parser_parse_block_sequence_entry(parser, event, first);
}

int bridge_yaml_parser_parse_indentless_sequence_entry(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_indentless_sequence_entry(parser, event);
}

int bridge_yaml_parser_parse_block_mapping_key(yaml_parser_t *parser, yaml_event_t *event, int first) {
    return yaml_parser_parse_block_mapping_key(parser, event, first);
}

int bridge_yaml_parser_parse_block_mapping_value(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_block_mapping_value(parser, event);
}

int bridge_yaml_parser_parse_flow_sequence_entry(yaml_parser_t *parser, yaml_event_t *event, int first) {
    return yaml_parser_parse_flow_sequence_entry(parser, event, first);
}

int bridge_yaml_parser_parse_flow_sequence_entry_mapping_key(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_flow_sequence_entry_mapping_key(parser, event);
}

int bridge_yaml_parser_parse_flow_sequence_entry_mapping_value(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_flow_sequence_entry_mapping_value(parser, event);
}

int bridge_yaml_parser_parse_flow_sequence_entry_mapping_end(yaml_parser_t *parser, yaml_event_t *event) {
    return yaml_parser_parse_flow_sequence_entry_mapping_end(parser, event);
}

int bridge_yaml_parser_parse_flow_mapping_key(yaml_parser_t *parser, yaml_event_t *event, int first) {
    return yaml_parser_parse_flow_mapping_key(parser, event, first);
}

int bridge_yaml_parser_parse_flow_mapping_value(yaml_parser_t *parser, yaml_event_t *event, int empty) {
    return yaml_parser_parse_flow_mapping_value(parser, event, empty);
}

int bridge_yaml_parser_process_empty_scalar(yaml_parser_t *parser, yaml_event_t *event, yaml_mark_t mark) {
    return yaml_parser_process_empty_scalar(parser, event, mark);
}

int bridge_yaml_parser_process_directives(yaml_parser_t *parser, yaml_version_directive_t **version_directive_ref, yaml_tag_directive_t **tag_directives_start_ref, yaml_tag_directive_t **tag_directives_end_ref) {
    return yaml_parser_process_directives(parser, version_directive_ref, tag_directives_start_ref, tag_directives_end_ref);
}

int bridge_yaml_parser_append_tag_directive(yaml_parser_t *parser, yaml_tag_directive_t value, int allow_duplicates, yaml_mark_t mark) {
    return yaml_parser_append_tag_directive(parser, value, allow_duplicates, mark);
}
