/* AUTO-GENERATED by cov/gen_bridges.py — do not edit. */
#include "/home/leochanj/Desktop/libyaml/src/api.c"

int bridge_yaml_string_read_handler(void *data, unsigned char *buffer, size_t size, size_t *size_read) {
    return yaml_string_read_handler(data, buffer, size, size_read);
}

int bridge_yaml_file_read_handler(void *data, unsigned char *buffer, size_t size, size_t *size_read) {
    return yaml_file_read_handler(data, buffer, size, size_read);
}

int bridge_yaml_string_write_handler(void *data, unsigned char *buffer, size_t size) {
    return yaml_string_write_handler(data, buffer, size);
}

int bridge_yaml_file_write_handler(void *data, unsigned char *buffer, size_t size) {
    return yaml_file_write_handler(data, buffer, size);
}

int bridge_yaml_check_utf8(const yaml_char_t *start, size_t length) {
    return yaml_check_utf8(start, length);
}
