#!/usr/bin/env bash
set -euo pipefail

# extract_branches.sh — extract branch count using LLVM coverage.
# Compiles all C source with coverage instrumentation, runs a trivial binary,
# then uses llvm-cov report to get the definitive branch count.
#
# Output: branches.md with per-file branch counts and total.
# Also outputs branch_total.txt with just the number for scripts.
#
# Uses same compilation approach as measure_coverage.sh:
# - Links all .o directly (not archive) for consistent counting
# - Excludes doc-only files
# - Uses -O0 -fno-builtin
#
# Usage: extract_branches.sh <output_file>

OUTPUT="${1:?Usage: extract_branches.sh <output_file>}"

if [ -f "$OUTPUT" ] && [ -s "$OUTPUT" ]; then
    echo "Branches already extracted: ${OUTPUT} ($(wc -l < "$OUTPUT") lines)"
    exit 0
fi

LIBMCS="${LIBMCS:-${TEST_CASE_DIR:-}}"
C_SRC_DIRS="${C_SRC_DIRS:-${LIBMCS}/mathd ${LIBMCS}/mathf ${LIBMCS}/common ${LIBMCS}/complexd ${LIBMCS}/complexf}"
C_INCLUDE_DIRS="${C_INCLUDE_DIRS:-${LIBMCS}/include}"
CC="${CC:-clang-21}"
LLVM_PROFDATA="${LLVM_PROFDATA:-llvm-profdata-21}"
LLVM_COV="${LLVM_COV:-llvm-cov-21}"

# Files to exclude (doc-only, no compiled code)
EXCLUDE_FILES="cmplx.c|isfinite.c|isgreater.c|isgreaterequal.c|isinf.c|isless.c|islessequal.c|islessgreater.c|isnan.c|isnormal.c|isunordered.c|fenv.c"

echo "Extracting branch info (LLVM)..."

BDIR=$(mktemp -d)
trap 'rm -rf "$BDIR"' EXIT

INC_FLAGS=""
for d in $C_INCLUDE_DIRS; do INC_FLAGS="$INC_FLAGS -I$d"; done

COV_FLAGS="-fprofile-instr-generate -fcoverage-mapping -O0 -fno-builtin"

# Compile all library .c files
echo "  Compiling library..."
for d in $C_SRC_DIRS; do
    [ -d "$d" ] || continue
    find "$d" -name '*.c' -type f | grep -vE "$EXCLUDE_FILES" | while read -r cfile; do
        oname="${BDIR}/c_$(basename "$(dirname "$cfile")")_$(basename "$cfile" .c).o"
        $CC $INC_FLAGS $COV_FLAGS -c "$cfile" -o "$oname" 2>/dev/null || true
    done
done
OBJ_FILES=$(find "$BDIR" -name 'c_*.o' -type f | sort)

# Minimal main that calls sin to pull in at least one object
cat > "${BDIR}/main.c" << 'EOF'
#include <math.h>
int main(void) { volatile double x = sin(0.5); (void)x; return 0; }
EOF

# Link ALL .o files directly (not archive) — consistent with measure_coverage.sh
$CC $INC_FLAGS $COV_FLAGS "${BDIR}/main.c" $OBJ_FILES \
    -lm -Wl,--allow-multiple-definition \
    -o "${BDIR}/branch_bin" 2>/dev/null || {
    echo "Error: link failed" >&2
    exit 1
}

# Run to generate profdata
LLVM_PROFILE_FILE="${BDIR}/default.profraw" "${BDIR}/branch_bin" >/dev/null 2>&1 || true
$LLVM_PROFDATA merge -sparse "${BDIR}/default.profraw" -o "${BDIR}/coverage.profdata"

# Get per-file branch data from llvm-cov report (library files only)
$LLVM_COV report "${BDIR}/branch_bin" -instr-profile="${BDIR}/coverage.profdata" 2>/dev/null | \
    grep "libm/" > "${BDIR}/per_file.txt"

# Also get per-file branch locations from llvm-cov show for the feedback loop
echo "  Extracting branch locations..."
$LLVM_COV show "${BDIR}/branch_bin" \
    -instr-profile="${BDIR}/coverage.profdata" \
    --show-branches=count 2>/dev/null | \
awk '
/^\/.*\.c:$/ {
    n = split($0, a, "/")
    fname = substr(a[n], 1, length(a[n])-1)
    next
}
/Branch \(/ {
    match($0, /Branch \([0-9]+:[0-9]+\)/)
    if (RSTART > 0) print fname ", " substr($0, RSTART, RLENGTH)
}
' | sort -u > "${BDIR}/branch_locations.txt"

BRANCH_POINTS=$(wc -l < "${BDIR}/branch_locations.txt")

# Get total from llvm-cov report (the authoritative number)
TOTAL_BRANCHES=$(awk '{
    n = NF; b = $(n-2) + 0
    if ($(n) == "-") next; t += b
} END { print t }' "${BDIR}/per_file.txt")

{
    echo "# Branch coverage data for C library"
    echo "# Generated by: extract_branches.sh using ${CC}, ${LLVM_COV}"
    echo "# Branch points (from llvm-cov show): ${BRANCH_POINTS}"
    echo "# Total branches (from llvm-cov report): ${TOTAL_BRANCHES}"
    echo "# Note: branch points × 2 ≠ total branches because llvm-cov report"
    echo "#   counts additional implicit branches (short-circuit, ternary, etc.)"
    echo ""
    cat "${BDIR}/branch_locations.txt"
} > "$OUTPUT"

# Also save the total for other scripts
OUTPUT_DIR="$(dirname "$OUTPUT")"
echo "$TOTAL_BRANCHES" > "${OUTPUT_DIR}/branch_total.txt"

echo "  ${BRANCH_POINTS} branch points, ${TOTAL_BRANCHES} total branches -> ${OUTPUT}"
